# Environment configuration
settings:
  docker:
    requirements: requirements.txt
    environment:
      WANDB_DISABLED: "true"

# Model Control Plane configuration
model:
  name: YeOldeEnglishTranslator
  description: Model to translate from old to modern english
  tags: ["quickstart", "llm", "t5"]

# Configure the pipeline
parameters:
  data_url: 'https://storage.googleapis.com/zenml-public-bucket/quickstart-files/translations.txt'
  # model_type: "t5-small"  # Choose between t5-small and t5-large
  num_train_epochs: 1
  per_device_train_batch_size: 1
  gradient_accumulation_steps: 4
  dataloader_num_workers: 4

# Per step configuration
steps:
  split_dataset:
    parameters:
      subset_size: 0.1  # only use 10% of all available data
      train_size: 0.7
      test_size: 0.1
      eval_size: 0.2
      random_state: 42
